Little improvements
mild-blue/clockify-automation pull request #15
Opened 2023-02-16 08:56 UTC by kubantjan

2023-02-16 09:41 UTC, marazt commented on ClockifyAPI.py
> +        raise ValueError(f"project {project_name} not found or multiple projects with same name found")
Tohle bych rozdelil na dve chyby.

2023-02-16 09:42 UTC, marazt commented on ClockifyAPI.py
> +                projectId = self.get_project_id(projectName, workspace, skip_prj_query=self._syncProjects)
Proc neni _syncProjects take prejmenvoana?

2023-02-16 09:42 UTC, marazt commented on ClockifyAPI.py
>      def archiveProject(self, projectName, workspace, skipPrjQuery=False):
tady skipPrjQuery a projectName nejsou moc Python style

2023-02-16 09:48 UTC, kubantjan commented on ClockifyAPI.py
>      def archiveProject(self, projectName, workspace, skipPrjQuery=False):
Jako souhlas jen jsem začal pomalu přejmenovat a nechtělo se mi to dělat celý na to teď nemám čas

2023-02-16 09:49 UTC, kubantjan commented on ClockifyAPI.py
> +        raise ValueError(f"project {project_name} not found or multiple projects with same name found")
No jasně ale tak jako ten kód na spoustu větších problémů tak zas další if se mi řešit nechtěl.

2023-02-16 10:20 UTC, kubantjan commented on ClockifyAPI.py
> +                projectId = self.get_project_id(projectName, workspace, skip_prj_query=self._syncProjects)
protoze je toho k prejmenovani milion :D asi bych

2023-02-16 10:21 UTC, kubantjan commented
@marazt  diky za review, ale fakt bych ted ty codestyles moc nehrotil a spis mrkni jen na tu logiku, to je jinak tak na 2 hodiny to vsechno prejmenovat a uklidit..

2023-03-07 13:01 UTC, tomaskourim requested changes

2023-03-07 13:35 UTC, kubantjan commented on main.py
> +            else:
no takhle funguje clockify, ze kdyz je projekt jako celek neco tak podle toho se urci default. 

ja takhle jsem zvyklej a dost mi to dava smysl, pro me je opruz pridavat furt billable vsude a prave mi vyhovuje ze vyuzivam toho, co je default na danym projektu. 

ono je problem ze ty v podstate nikdy billable veci nemas, kdezto ja sem tam jo. Rekl bych ze aby obecne byl ten tool uzitecnej pro prumernyho mild blue cloveka, tak je moje reseni lepsi. 

Ale pro tebe konkretne mozna chces mit ten case ze by default je vsechno non-billable i na billable projektech.

Tak tam asi muzeme pridat nejaky flag do configu no :D.

2026-05-19 08:05 UTC, closed without merging