Filter user and Delete existing config
mild-blue/clockify-automation pull request #6
Opened 2021-02-28 09:14 UTC by LukasForst

2021-02-28 09:29 UTC, marazt commented on main.py
> +            if config.get('ToggleFilterUser') and config['ToggleFilterUser'] != row['Email']:
tags = list(filter(lambda x: x != '', map(lambda y: y.strip(), row['Tags'].split(','))))

2021-02-28 10:25 UTC, LukasForst commented on main.py
> +            if config.get('ToggleFilterUser') and config['ToggleFilterUser'] != row['Email']:
asi myslis jinou radku, ale proc takhle? ten `strip` tam v soucasnosti je a list comprehensions jsou vic "pythonic"
```python
tags = [tag.strip() for tag in row['Tags'].split(',') if tag.strip() != '']
```

2021-03-01 17:02 UTC, tomaskourim requested changes
drobne

2021-03-01 18:17 UTC, LukasForst commented on README.md
> +- `DeleteExistingFrom` - delete all entries from Clockify starting from the `From` date (*NOTE: that it even deletes
o par radku pod tim, mas priklad, kde je to evidentne boolean 😃 ale ok

2021-03-03 10:57 UTC, tomaskourim approved these changes
za me ok, @marazt ?

2021-03-06 09:58 UTC, tomaskourim commented
@marazt mergujeme?

2021-03-06 10:17 UTC, merged